// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZVHLxZmXCiFVf4dcIR-PSF3kDMERx8U',
    appId: '1:118964058790:android:c7f0b2c343c14c03af9267',
    messagingSenderId: '118964058790',
    projectId: 'talkease-renew',
    storageBucket: 'talkease-renew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC21p9Wj6JK1teoSEIUN3jholwK6pMA-Ns',
    appId: '1:118964058790:ios:02d46417e21213c0af9267',
    messagingSenderId: '118964058790',
    projectId: 'talkease-renew',
    storageBucket: 'talkease-renew.appspot.com',
    androidClientId: '118964058790-gdlort1p8lmfeuilccoksta4hu3g556a.apps.googleusercontent.com',
    iosClientId: '118964058790-gn0aefqiv7p9jl61odf4ed07h6joi9sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
